<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../DraftTG.Application/DraftTG.Application.csproj" />
  </ItemGroup>
</Project>
